
CREATE TABLE ACCOUNT(
  ACC_EMAIL VARCHAR(100) NOT NULL PRIMARY KEY,
  ACC_PASS CHAR(32) NOT NULL,
  ACC_FNAME VARCHAR(25) NOT NULL,
  ACC_LNAME VARCHAR(25) NOT NULL,
  ACC_ADDRESS VARCHAR (200) NOT NULL,
  ACC_TYPE VARCHAR(12) NOT NULL,
  ACC_TEMP_PASS VARCHAR(32),
  ACC_TEMP_PASS_EXPIRES DATETIME
);