

/* Database Password:  tyrjh%idl*kasdfasdfE  */


CREATE USER 'timely'@'localhost' IDENTIFIED BY 'tyrjh%idl*kasdfasdfE';
GRANT ALL PRIVILEGES ON * . * TO 'timely'@'localhost';
FLUSH PRIVILEGES;

CREATE DATABASE timely;
USE timely;


CREATE TABLE ACCOUNT(
  ACC_EMAIL VARCHAR(100) NOT NULL PRIMARY KEY,
  ACC_PASS CHAR(32) NOT NULL,
  ACC_FNAME VARCHAR(25) NOT NULL,
  ACC_LNAME VARCHAR(25) NOT NULL,
  ACC_PHONE INT NOT NULL,
  ACC_ADDRESS VARCHAR (200) NOT NULL,
  ACC_TYPE VARCHAR(12) NOT NULL,
  ACC_DRIVER VARCHAR(100) NOT NULL,
  ACC_TEMP_PASS VARCHAR(32),
  ACC_TEMP_PASS_EXPIRES DATETIME
);