

/* Database Password:  tyrjh%idl*kasdfasdfE  */


CREATE USER 'timely'@'localhost' IDENTIFIED BY 'tyrjh%idl*kasdfasdfE';
GRANT ALL PRIVILEGES ON * . * TO 'timely'@'localhost';
FLUSH PRIVILEGES;

CREATE DATABASE timely;
USE timely;


CREATE TABLE ACCOUNT(
  ACC_EMAIL VARCHAR(100) NOT NULL PRIMARY KEY,
  ACC_PASS CHAR(32) NOT NULL,
  ACC_FNAME VARCHAR(25) NOT NULL,
  ACC_LNAME VARCHAR(25) NOT NULL,
  ACC_PHONE VARCHAR (10) NOT NULL,
  ACC_ADDRESS VARCHAR (200) NOT NULL,
  ACC_TYPE VARCHAR(12) NOT NULL,
  ACC_DRIVER VARCHAR(100) NOT NULL,
  ACC_TEMP_PASS VARCHAR(32),
  ACC_TEMP_PASS_EXPIRES DATETIME
);

CREATE TABLE ORDERED(
  ORD_NUM INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  ORD_DEL_ADDR VARCHAR(250) NOT NULL,
  ORD_STORE_ADDR VARCHAR(250) NOT NULL,
  ORD_DRIVER VARCHAR(100) NOT NULL,
  ORD_CUSTOMER VARCHAR(100) NOT NULL,
  ORD_DATE_PLACED TIMESTAMP  DEFAULT CURRENT_TIMESTAMP NOT NULL,
  ORD_DELIVERED TIMESTAMP,
  FOREIGN KEY (ORD_DRIVER) REFERENCES ACCOUNT(ACC_EMAIL),
  FOREIGN KEY (ORD_CUSTOMER) REFERENCES ACCOUNT(ACC_EMAIL)
);

CREATE TABLE ITEMS(
 ITEM_ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
 ORD_NUM INT NOT NULL,
 ITEM_NUMBER INT,
 ITEM_NAME VARCHAR(250) NOT NULL,
 ITEM_IMG VARCHAR(200),
 ITEM_BRAND VARCHAR(100),
 ITEM_PRICE FLOAT(15),
 ITEM_DESC VARCHAR(300),
 FOREIGN KEY (ORD_NUM) REFERENCES ORDERED(ORD_NUM)
);